AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Serverless Form Handler - accepts a form submission from a webpage, saving the data to a DynamoDB table and sending an email via SES.
Parameters:
  ValidatedEmail:
    Type: String
    Default: validated@email.com
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
Globals:
  Function:
    Timeout: 10
  Api:
    EndpointConfiguration: EDGE
    Cors:
      AllowMethods: '''OPTIONS,POST'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
Resources:
  FormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: formId
          AttributeType: S
      KeySchema:
        - AttributeName: formId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  SubmitFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Environment:
        Variables:
          ValidatedEmail: !Ref ValidatedEmail
          FormDataTable: !Ref FormDataTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FormDataTable
        - SESCrudPolicy:
            IdentityName: !Ref ValidatedEmail
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /submitForm
            Method: post
  GetFormData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-GetFormData
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: GetFormData
      CodeUri: src/
      Handler: app.get
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref FormDataTable
      Environment:
        Variables:
          TABLE_NAME: !Ref FormDataTable
          TABLE_ARN: !GetAtt FormDataTable.Arn
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /gettFormData
            Method: post
Outputs:
  SubmitFormFunction:
    Description: Lambda Function ARN
    Value: !GetAtt SubmitFormFunction.Arn
  SubmitFormFunctionIamRole:
    Description: Implicit IAM Role created for function
    Value: !GetAtt SubmitFormFunctionRole.Arn
  FormDataTable:
    Description: DynamoDB Table
    Value: !Ref FormDataTable